name: flamingo
channels:
- conda-forge
- defaults
dependencies:
- pip
- python=3.8 
#- pywps
- jinja2
- click
- psutil
# tests
- pytest
- rtree>=0.9
- cfunits
- cftime>=1.3.1
#- intake
#- intake-esm
- udunits2>=2.2
- xarray>=0.16
- dask>=2.26
- netcdf4>=1.4
#- daops>=0.3.0,<0.4
#- clisops>=0.4.0,<0.5
# workflow
- networkx
# provenance
- prov>=2.0.0
- graphviz
# tests
- pytest
- python-dateutil>=2.8.1
- gitpython
